# Generated by Django 3.1.5 on 2021-02-03 13:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('temp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=200)),
                ('Category', models.CharField(choices=[('The Climate Crisis', 'The Climate Crisis'), ('Food', 'Food'), ('Movies/Webseries', 'Movies/Webseries'), ('Programming', 'Programming'), ('Random', 'Random')], max_length=200, null=True)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='user/%Y/%m/%d/')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='BlogSite.post')),
            ],
        ),
    ]
